# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Wink' do

    pod 'AFNetworking', '~> 3.0'
    pod 'SVProgressHUD'
    pod 'FBSDKCoreKit'
    pod 'FBSDKShareKit'
    pod 'FBSDKLoginKit'
    pod 'CocoaLumberjack'
    pod 'AGEmojiKeyboard'
    pod 'Google-Mobile-Ads-SDK'
end
